### ISSUE TITLE
[Bug]: Clicking on the Hibiscus Bonus Points Social Media Links greys out the Buttons

### ISSUE THREAD

**Issue by elliotfayman** [HackSC/hibiscus#416]
### Contact Details

elliotfayman@gmail.com

### Description of bug

I clicked on the links for the hibiscus page to check whether or not the forms where open. I found out that they were not open however I now cannot re click on the buttons as they are now "pending" despite not submitting any forms. 

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

None

**Comment by VictiniX888** [comment]
Hi! We can confirm that this is the current implementation for the bonus points form; it will say pending once you submit the form, and we will change it to verified once it's verified!

We understand that this isn't very intuitive right now, we'll work on improving that! Sorry for any inconvenience caused!

**Comment by snokpok** [comment]
marking as resolved! thanks @elliotfayman for the notice
